<?php

/**
* @file
* Provides custom blocks for Pine River
*
* Modified to form to meet mock-up needs.
* Search options turned off, only does key word search
* Also Turned off the large search block component
*
* Pascal Brammeier 10-19-2015
*/

define('OPAC_SEARCH_TITLE_URL', '/Union/Search?searchSource=local&lookfor={text}&basicType=Title&genealogyType=GenealogyKeyword&submit=Find');
define('OPAC_SEARCH_AUTHOR_URL', '/Union/Search?searchSource=local&lookfor={text}&basicType=Author&genealogyType=GenealogyKeyword&submit=Find');
define('OPAC_SEARCH_SUBJECT_URL', '/Search/Results?lookfor={text}&type=Subject&submit=Find');
define('OPAC_SEARCH_KEYWORD_URL', '/Search/Results?lookfor={text}&type=Keyword&submit=Find');
define('LIBRARY_WEBSITE_SEARCH_URL', 'search/site/{text}');
define('OPAC_SEARCH_ITEM_URL', '');
/**
* Implements hook_block_info().
*/
function pika_blocks_block_info() {
	$blocks = array();

	$blocks['search_small'] = array(
		'info' => t('PIKA: Small search block'),
	);
//  $blocks['search_large'] = array(
//    'info' => t('PIKA: Large search block'),
//  );

	return $blocks;
}

/**
* Implements hook_block_view().
*/
function pika_blocks_block_view($delta = '') {
	$block = array();

	switch ($delta) {
		case 'search_small':
			$block['subject'] = t('');
//      $block['subject'] = t('SEARCH');
			$block['content'] = pika_blocks_search_small();
			break;

//    case 'search_large':
//      $block['subject'] = t('SEARCH the CATALOG');
//      $block['content'] = pika_blocks_search_large();
//      break;
	}

	return $block;
}

/**
* Small search form.
*/
function pika_blocks_search_small() {
	return drupal_get_form('pika_blocks_search_small_form');
}

function pika_blocks_search_small_form() {
	$form = array();

	$form['#action'] = url('<front>');

	$form['text'] = array(
		'#type' => 'textfield',
		'#attributes' => array(
			'placeholder' => t('Search'),
		),

		/**'#title' => t('Search for'),*/
		//    '#size' => 20,
	);

	$form['submit'] = array(
		'#type' => 'submit',
		//    '#value' => '&#128269;',
		'#value' => 'Go',
	);


	// Original
	//  $form['type'] = array(
	//    '#type' => 'radios',
	//    /**'#title' => t('Search'),*/
	//    '#default_value' =>'catalog',
	//    '#options'=>array(
	//      'catalog'=> t('Catalog'),
	//      'website'=> t('Website'),
	//    ),
	//  );

	return $form;
}

	function pika_blocks_search_small_form_submit($form, &$form_state) {
	$url = '';
	$search_term = urlencode($form_state['values']['text']);
	$url = preg_replace('/\{text\}/', $search_term, variable_get('pika_blocks_opac_url') . OPAC_SEARCH_KEYWORD_URL);


	switch ($form_state['values']['type']) {
	//    case 'catalog':
	//      $url = preg_replace('/\{text\}/', $search_term, OPAC_SEARCH_KEYWORD_URL);
	//      break;
	//    case 'title':
	//      $url = preg_replace('/\{text\}/', $search_term, variable_get('pika_blocks_opac_url') . OPAC_SEARCH_TITLE_URL);
	//      break;
	//    case 'author':
	//      $url = preg_replace('/\{text\}/', $search_term, variable_get('pika_blocks_opac_url') . OPAC_SEARCH_AUTHOR_URL);
	//      break;
	//    case 'subject':
	//      $url = preg_replace('/\{text\}/', $search_term, variable_get('pika_blocks_opac_url') . OPAC_SEARCH_SUBJECT_URL);
	//      break;


	case 'website':
	$url = preg_replace('/\{text\}/', $search_term, LIBRARY_WEBSITE_SEARCH_URL);
	break;
	case 'catalog':
	default:
	$url = preg_replace('/\{text\}/', $search_term, variable_get('pika_blocks_opac_url') . OPAC_SEARCH_KEYWORD_URL);
	break;
	}

	drupal_goto($url);
	}

function pika_blocks_menu(){
//	//Main browse
//	//TODO: Should the callback just send us to Pika?
//	//No the callback should not send us to Pika because then we can never see the sublinks.
//	$items['browse'] = array(
//		'title' => 'Browse Pika',
//		'access callback' => true,
//		'page callback' => 'drupal_goto',
//		'page arguments' => array(
//			variable_get('pika_blocks_opac_url'),
//		),
//	);
//	//Create sub menus
//	//Call the API to see what browse categories the user has active
//	$api_result = file_get_contents(variable_get('pika_blocks_opac_url') . "/Browse/AJAX?method=getActiveBrowseCategories");
//	//Transform what we got from the API into JSON
//	$api_json = json_decode($api_result);
//
//	//Create sub menus
//	$i = 0;
//	foreach ($api_json as $browse_category_info){
//		$items['browse/' . $browse_category_info->text_id] = array(
//			'title' => $browse_category_info->display_label,
//			'access callback' => true,
//			'page callback' => 'drupal_goto',
//			'page arguments' => array(
//				$browse_category_info->link
//			),
//			'weight' => $i++
//		);
//	}

	//Add a configuration block for the module
	$items['admin/config/search/pika_blocks'] = array(
		'title' => 'Pika Integration',
		'description' => 'Configuration for Pika administration',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('pika_blocks_form'),
		'access arguments' => array('configure pika integration'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

function pika_blocks_permission(){
	return array(
		'configure pika integration' => array(
			'title' => t('Configure Pika Integration'),
		)
	);
}

function pika_blocks_form($form, &$form_state){
	$form['pika_blocks_opac_url'] = array(
		'#type' => 'textfield',
		'#title' => t('OPAC URL'),
		'#default_value' => variable_get('pika_blocks_opac_url', 'http://opac.marmot.org'),
		'#size' => 60,
		'#maxlength' => 255,
		'#description' => t('The base url of the OPAC instance to connect to for searching and display of browse category information'),
		'#required' => TRUE,
	);

	return system_settings_form($form);
}

function pika_blocks_form_validate($form, &$form_state){
	//Make sure that the URL passed in is an actual url
	$newValue = $form_state['values']['pika_blocks_opac_url'];
	if (!filter_var($newValue, FILTER_VALIDATE_URL)) {
		form_set_error('opac_url', 'Sorry it doesn\'t look like you provided a valid url');
	}
}

	/**
	* Large search form.
	*/
	//function pika_blocks_search_large() {
	//  return drupal_get_form('pika_blocks_search_large_form');
	//}

	//function pika_blocks_search_large_form() {
	//  $form = array();
	//
	// $form['text'] = array(
	//    '#type' => 'textfield',
	//    /**'#title' => t('Search for'), */
	//    '#size' => 20,
	//  );
	//
	// $form['radio'] = array(
	//    '#type' => 'radios',
	//    /**'#title' => t('Search type'),*/
	//    '#options' => array(
	//      'keyword' => t('Keyword'),
	//      'title' => t('Title'),
	//      'author' => t('Author'),
	//      'subject' => t('Subject'),
	//      'website' => t('Website'),
	//    ),
	//  );
	//
	//
	//
	//  $form['branch'] = array(
	//    '#type' => 'radios',
	//    /**'#title' => t('Search branch'),*/
	//      '#default_value'=>'',
	//    '#options' => array (
	//      '' => t('All'),
	//      'GCP+Carbondale+Branch' => t('Carbondale'),
	//        'GCP+Glenwood+Branch' => t('Glenwood Springs'),
	//      'GCP+New+Castle+Branch' => t('New Castle'),
	//      'GCP+Parachute+Branch' => t('Parachute'),
	//      'GCP+Silt+Branch' => t('Silt'),
	//      'GCP+Rifle+Branch' => t('Rifle'),
	//     ),
	//  );
	//
	//
	//
	//  $form['submit'] = array(
	//    '#type' => 'submit',
	//    '#value' => t('Search'),
	//      );
	//
	//  return $form;
	//}
	//
	//function pika_blocks_search_large_form_submit($form, &$form_state) {
	//  $url = '';
	//  $search_term = urlencode(($form_state['values']['text']));
	//
	//  switch ($form_state['values']['type']) {
	//    case 'keyword':
	//      $url = preg_replace('/\{text\}/', $search_term, OPAC_SEARCH_KEYWORD_URL);
	//      break;
	//    case 'title':
	//      $url = preg_replace('/\{text\}/', $search_term, OPAC_SEARCH_TITLE_URL);
	//      break;
	//    case 'author':
	//      $url = preg_replace('/\{text\}/', $search_term, OPAC_SEARCH_AUTHOR_URL);
	//      break;
	//    case 'subject':
	//      $url = preg_replace('/\{text\}/', $search_term, OPAC_SEARCH_SUBJECT_URL);
	//      break;
	//    case 'website':
	//      $url = preg_replace('/\{text\}/', $search_term, LIBRARY_WEBSITE_SEARCH_URL);
	//      break;
	//    default:
	//      $url = preg_replace('/\{text\}/', $search_term, OPAC_SEARCH_KEYWORD_URL);
	//      break;
	//  }
	//
	//  if ($form_state['values']['branch']) {
	//    $url .= "&filter[]=building:\"". $form_state['values']['branch'] ."\"";
	//  }
	//
	//  drupal_goto($url);
	//}
